### ISSUE TITLE
enml2html代码块无法正常换行问题

### ISSUE THREAD

**Issue by itgoyo** [zhougy0717/everblog-adaptor-hexo-html#1]
![](http://omvbl46i3.bkt.clouddn.com/18-8-23/44593760.jpg)

新版evernote已经支持Markdown,但是在使用Markdown代码块转成html的时候，不能正常换行，显示比较诡异，这个有什么法子优化么？

**Comment by zhougy0717** [comment]
我好久没更新blog了，前两天想用来着，结果token被印象收回了。我还在要那个token。要来之后我再去试试看。windows版本可以用markdown了吗？因为我之前都是用马克飞象写markdown。不知道这两者渲染出来的有什么不一样。估计又得花点时间debug一下了。

**Comment by itgoyo** [comment]
好的，有时间的话，您那边看一下，现在是mac版在20号已经支持了，win版后面也快支持了。

**Comment by zhougy0717** [comment]
OK。那可能要等win版发布了。我没有MAC电脑。

**Comment by zhougy0717** [comment]
我感觉以后是不是已经不需要这个html的adapter了，evernote支持markdown，hexo也支持markdown。只要把笔记文本抓出来就可以了，然后用hexo
generate就能生成博客了

**Comment by zhougy0717** [comment]
fix掉了
在enml2html的时候，把换行移除了。我已经提了PR到主仓了
